### ISSUE TITLE
Can we move this to solidusio-contrib?

### ISSUE THREAD

**Issue by aldesantis** [solidusio-contrib/solidus_klarna_payments#18]
@josetonyp hey there! 👋 Klarna integration is part of the Solidus roadmap for 2020, and we want to reuse existing code wherever possible in order to minimize the effort and make good use of community work.

I saw that this extension is not actively maintained anymore, and I was wondering if you'd be up for moving it to solidusio-contrib and giving the core team access to the gem on RubyGems? We want to make it fully compatible with the currently maintained versions of the 2.x branch, bring it up to speed with the new extension defaults, and release a new version on RubyGems.

We're also happy to fork it of course but transferring the repository would be better since it creates less confusion in the community. Of course, we'd give you full credit for the original implementation and you'd still be a maintainer.

**Comment by josetonyp** [comment]
@aldesantis Thanks for you message. I'll be glad to move it to solidusio-contrib so you can continue the development of this Gem further. I think @robinboening can do that for us as he is the admin of this repository.

**Comment by aldesantis** [comment]
Cool, you guys let me know! 🙂

**Comment by MrFehr** [comment]
@aldesantis I'm currently trying to get this working on a website in the UK. Have you managed to get it working yourself? I have a few decorators fixing a couple of problems but not there yet 😁

**Comment by aldesantis** [comment]
@MrFehr sorry, we haven't actually started any work on this as we don't use Klarna on any of the stores we maintain.

@robinboening I was wondering if you've had a chance to check this out? 🙏

**Comment by robinboening** [comment]
Hey all,

sorry for the delayed response. I am happy to move the repo over to solidusio-contrib (since @josetonyp already agreed there is nothing against it).

@aldesantis since I am not part of the solidusio-contrib org I can not transfer ownership directly to it. I could assign you and you'll move it. Or any other idea?

**Comment by aldesantis** [comment]
@robinboening that sounds good, thanks so much!

**Comment by MrFehr** [comment]
@aldesantis no problem. I don't know how to submit patches, so below is my working changes. Not much was needed to get it working.

#### Migrations issue during klarna_gateway:install
All migrations need to be changed from `ActiveRecord::Migration` to `ActiveRecord::Migration[4.2]`

#### klarna/credit.rb (klarna_client)
```
def create_session(data)
  do_request(:post, "/credit/v1/sessions") do |request|
    request.body = data.to_json
  end
end

def update_session(session_id, data)
  do_request(:post, "/credit/v1/sessions/#{session_id}") do |request|
    request.body = data.to_json
  end
end

def place_order(authorization_token, data)
  do_request(:post, "/credit/v1/authorizations/#{authorization_token}/order") do |request|
    request.body = data.to_json
  end
end
```


#### klarna_gateway/controllers/admin/payment_methods_controller.rb (solidus_klarna_payments)
```
def validate_klarna_credentials
  if params[:payment_method][:type] == 'Spree::Gateway::KlarnaCredit'
    if (params[:payment_method][:preferred_api_secret].blank? || params[:payment_method][:preferred_api_key].blank?)
      flash[:error] = Spree.t('klarna.can_not_test_api_connection')
    end

    if params[:payment_method][:preferred_api_secret].present? && params[:payment_method][:preferred_api_key].present?
      Klarna.configure do |config|
        config.environment = !Rails.env.production? ? 'test' : 'production'
        config.country = params[:payment_method][:preferred_country]
        config.api_key =  params[:payment_method][:preferred_api_key]
        config.api_secret = params[:payment_method][:preferred_api_secret]
        config.user_agent = "Klarna Solidus Gateway/#{::KlarnaGateway::VERSION} Solidus/#{::Spree.solidus_version} Rails/#{::Rails.version}"
      end

      klarna_response = Klarna.client(:credit).create_session({})

      if klarna_response.code == 401
        flash[:error] = Spree.t('klarna.invalid_api_credentials')
      else
        flash[:notice] = Spree.t('klarna.valid_api_credentials')
      end
    end
  end
end
```


`/app/models/spree/klarna_credit_payment.rb` (solidus_klarna_payments)
```
belongs_to :user, class_name: Spree::UserClassHandle.new, foreign_key: 'user_id'
belongs_to :order, class_name: "Spree::Order", foreign_key: 'spree_order_id'
```

Hope this helps 👍🏻

**Comment by robinboening** [comment]
> @robinboening that sounds good, thanks so much!

@aldesantis I sent a repo transfer request. Did you see?

**Comment by aldesantis** [comment]
@robinboening sorry, I think it expired. 😞 Could you try again? Thanks!

**Comment by robinboening** [comment]
@aldesantis No worries, I just triggered the transfer again.

**Comment by aldesantis** [comment]
@robinboening this now has a new home. Thanks so much, we'll take good care of it! 🙂
